//
//  lokiStructure.h
//  Loki_Tools
/*
 Loki Tools a Search engine, data preperation tool that does data mining
 and retail analysis.
 Copyright (C) 2011  Douglas Mason
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 
 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.//
 */

/*
	LOKI DATABASE TABLE STRUCTURE NAMES
 */

#define TRADER_TABLE @"TRADER_TYPE"
//TABLE ROWS
#define TRADER_TABLE_TYPE @"TITLE"
#define TRADER_TABLE_DESCRIPTION @"SUMMARY"
#define TRADER_TABLE_REBATE @"PERCENT_REBATE"

//TABLE NAME
#define SUPPLIER_TABLE @"SUPPLIER"
//TABLE ROWS
#define SUPPLIER_TABLE_CODE @"SUPPLIER_CODE"
#define SUPPLIER_TABLE_NAME @"TRADE_NAME"
#define SUPPLIER_TABLE_POSTAL_ADD @"POSTAL_ADDRESS"
#define SUPPLIER_TABLE_PHYSICAL_ADD @"PHYSCIAL_ADDRESS"
#define SUPPLIER_TABLE_PHONE @"PHONE"
#define SUPPLIER_TABLE_FAX @"FAX"
#define SUPPLIER_TABLE_EMAIL @"EMAIL"
#define SUPPLIER_TABLE_WEBSITE @"WEBSITE"
#define SUPPLIER_TABLE_FREIGHT_FREE_LIMIT @"FREIGHT_FREE_LIMIT"
#define SUPPLIER_TABLE_TRADER_TYPE @"TRADER"
#define SUPPLIER_TABLE_LOGO @"LOGO"

//TABLE NAME
#define SUPPLIER_EMPLOYEES_TABLE @"SUPPLIER_EMPLOYEES"
//TABLE ROWS
#define SUPPLIER_EMPLOYEES_TABLE_CODE @"SUPPLIER_CODE"
#define SUPPLIER_EMPLOYEES_TABLE_NAME @"EMPLOYEE_NAME"
#define SUPPLIER_EMPLOYEES_TABLE_PHONE @"PHONE"
#define SUPPLIER_EMPLOYEES_TABLE_MOBILE @"MOBILE"
#define SUPPLIER_EMPLOYEES_TABLE_EMAIL @"EMAIL"
#define SUPPLIER_EMPLOYEES_TABLE_ID_NO @"ID_PERSON"

//TABLE NAME
#define STORE_TABLE @"STORE"
//TABLE ROWS
#define STORE_TABLE_NAME @"TRADE_NAME"
#define STORE_TABLE_POSTAL_ADD @"POSTAL_ADDRESS"
#define STORE_TABLE_PHYSICAL_ADD @"PHYSICAL_ADDRESS"
#define STORE_TABLE_PHONE @"PHONE"
#define STORE_TABLE_FAX @"FAX"
#define STORE_TABLE_EMAIL @"EMAIL"
#define STORE_TABLE_WEBSITE @"WEBSITE"
#define STORE_TABLE_FREE_PHONE @"FREE_PHONE"
#define STORE_TABLE_FREE_FAX @"FREE_FAX"
#define STORE_TABLE_COMPANY_PROFILE @"COMPANY_PROFILE"
#define STORE_TABLE_MARKET @"PRODUCT_CUSTOMER_MARKET"
#define STORE_TABLE_EXPERTISE @"EXPERTISE"
#define STORE_TABLE_BRANDS @"KEY_BRANDS"
#define STORE_TABLE_CODE @"STORE_CODE"

//TABLE NAME
#define STORE_EMPLOYEES_TABLE @"STORE_EMPLOYEES"
//TABLE ROWS
#define STORE_EMPLOYEES_TABLE_NAME @"EMPLOYEE_NAME"
#define STORE_EMPLOYEES_TABLE_CODE @"STORE_CODE"
#define STORE_EMPLOYEES_TABLE_PHONE @"PHONE"
#define STORE_EMPLOYEES_TABLE_MOBILE @"MOBILE"
#define STORE_EMPLOYEES_TABLE_EMAIL @"EMAIL"
#define STORE_EMPLOYEES_TABLE_ID_NO @"ID_EMPLOYEE"

//TABLE NAME
#define DISCOUNTS_TABLE @"DISCOUNTS"
//TABLE ROWS
#define DISCOUNTS_TABLE_SUPPLIER_CODE @"SUPPLIER_CODE"
#define DISCOUNTS_TABLE_STORE_CODE @"STORE_CODE"
#define DISCOUNTS_TABLE_TYPE @"TITLE"
#define DISCOUNTS_TABLE_DISCOUNT @"DISCOUNT"

//TABLE NAME
#define PRODUCT_TABLE @"PRODUCT"
//TABLE ROWS
#define PRODUCT_TABLE_SUPPLIER_CODE @"SUPPLIER_CODE"
#define PRODUCT_TABLE_PART_NO @"SUPPLIER_PART_NO"
#define PRODUCT_TABLE_DESCRIPTION @"PRODUCT_DESCRIPTION"
#define PRODUCT_TABLE_BRAND @"BRAND"
#define PRODUCT_TABLE_UNIT @"UNIT"
#define PRODUCT_TABLE_BAR_CODE @"SUPPLIER_BAR_CODE"
#define PRODUCT_TABLE_PACK_QUANTITY @"PACK_QUANTITY"
#define PRODUCT_TABLE_CATALOGUE_PAGE @"CATALOGUE_PAGE"
#define PRODUCT_TABLE_STOCKED_INDENT @"STOCKED_INDENT"
#define PRODUCT_TABLE_DETAILS @"PRODUCT_DETAILS"
#define PRODUCT_TABLE_PICTURE @"PICTURE"
#define PRODUCT_TABLE_BRAND_LOGO @"BRAND_LOGO"
//PROMOTION FIELDS REDUNDENT AS OF 8TH AUGUST 2011
//USE NEW PROMOTION TABLE FOR THIS INFORMATION
#define PRODUCT_TABLE_PROMOTION_DETAILS @"PROMOTION_DETAILS"
#define PRODUCT_TABLE_PROMOTION_ID @"PROMOTION_ID"
#define PRODUCT_TABLE_PROMO_PAGE_NO @"PROMO_PAGE_NO"
//*********************************
#define PRODUCT_TABLE_COMMENTS @"COMMENTS"
#define PRODUCT_TABLE_DISCONTINUED @"DISCONTINUED"

//TABLE NAME
#define PRICES_TABLE @"PRODUCT_PRICES"
//TABLE ROWS
#define PRICES_TABLE_STORE_CODE @"STORE_CODE"
#define PRICES_TABLE_SUPPLIER_CODE @"SUPPLIER_CODE"
#define PRICES_TABLE_SUPPLIER_PART_NO @"SUPPLIER_PART_NO"
#define PRICES_TABLE_LIST_PRICE @"LIST_PRICE"
#define PRICES_TABLE_PACK_LIST_PRICE @"PACK_LIST_PRICE"
#define PRICES_TABLE_PACK_DISCOUNT_CODE @"PACK_DISCOUNT_CATAGORY"
#define PRICES_TABLE_BROKEN_PACK_DISCOUNT_CODE @"BROKEN_PACK_DISCOUNT_CATAGORY"
#define PRICES_TABLE_NETT_CONTRACT_PRICE @"NETT_CONTRACT_PRICE"
//PROMOTION PRICES REDUNDENT AS OF 8TH AUGUST 2011
//USE NEW PROMOTION TABLE FOR THIS INFORMATION
#define PRICES_TABLE_PROMO_BUY_PRICE @"PROMO_BUY_PRICE"
#define PRICES_TABLE_PROMO_SELL_EX_GST @"PROMO_SELL_EX_GST"
#define PRICES_TABLE_PROMO_SELL_INC_GST @"PROMO_SELL_INC_GST"
//**********************************
#define PRICES_TABLE_STOCK_ON_HAND @"STOCK_ON_HAND"
#define PRICES_TABLE_ORDER @"QUANTITY_TO_ORDER"

//TABLE NAME
#define CUSTOMER_TABLE @"CUSTOMER"
//TABLE ROWS
#define CUSTOMER_TABLE_STORE_CODE @"STORE_CODE"
#define CUSTOMER_TABLE_CUSTOMER_CODE @"CUSTOMER_CODE"
#define CUSTOMER_TABLE_CUSTOMER_NAME @"CUSTOMER_NAME"
#define CUSTOMER_TABLE_POSTAL_ADD @"POSTAL_ADDRESS"
#define CUSTOMER_TABLE_PHYSICAL_ADD @"PHYSCIAL_ADDRESS"
#define CUSTOMER_TABLE_PHONE_PERSONAL @"PHONE_PERSONAL"
#define CUSTOMER_TABLE_PHONE_WORK @"PHONE_WORK"
#define CUSTOMER_TABLE_MOBILE @"MOBILE"
#define CUSTOMER_TABLE_EMAIL @"EMAIL"

//TABLE NAME
#define PRODUCT_STORE_TABLE @"PRODUCT_STORE"
//TABLE ROWS
#define PRODUCT_STORE_TABLE_STORE_CODE @"STORE_CODE"
#define PRODUCT_STORE_TABLE_PRODUCT_CODE @"PRODUCT_CODE"
#define PRODUCT_STORE_TABLE_PRODUCT_DESCRIPTION @"PRODUCT_DESCRIPTION"
#define PRODUCT_STORE_TABLE_SUPPLIER_PART_NO @"SUPPLIER_PART_NO"
#define PRODUCT_STORE_TABLE_SUPPLIER_CODE @"SUPPLIER_CODE"
#define PRODUCT_STORE_TABLE_STOCK_GROUP_CODE @"STOCK_GROUP_CODE"
#define PRODUCT_STORE_TABLE_SALES_GROUP_CODE @"SALES_GROUP_CODE"
#define PRODUCT_STORE_TABLE_STANDARD_COST @"STANDARD_COST"
#define PRODUCT_STORE_TABLE_LATEST_COST @"LATEST_COST"
#define PRODUCT_STORE_TABLE_AVERAGE_COST @"AVERAGE_COST"
#define PRODUCT_STORE_TABLE_EXC_MARKUP @"EXCLUSIVE_MARKUP"
#define PRODUCT_STORE_TABLE_MINIMUM_STOCK @"MINIMUM_STOCK"
#define PRODUCT_STORE_TABLE_MAXIMUM_STOCK @"MAXIMUM_STOCK"
#define PRODUCT_STORE_TABLE_MINIMUM_STOCK_RECOMMENDED @"MINIMUM_STOCK_RECOMMENDED"
#define PRODUCT_STORE_TABLE_MAXIMUM_STOCK_RECOMMENDED @"MAXIMUM_STOCK_RECOMMENDED"
#define PRODUCT_STORE_TABLE_STOCK_AVAILABLE @"STOCK_AVAILABLE"

//TABLE NAME
#define TRANSACTIONS_TABLE @"TRANSACTIONS"
//TABLE ROWS
#define TRANSACTIONS_TABLE_STORE_CODE @"STORE_CODE"
#define TRANSACTIONS_TABLE_TRANSACTION_ID @"TRANSACTION_ID"
#define TRANSACTIONS_TABLE_CUSTOMER_CODE @"CUSTOMER_CODE"
#define TRANSACTIONS_TABLE_PRODUCT_CODE @"PRODUCT_CODE"
#define TRANSACTIONS_TABLE_TRANSACTION_DAY @"TRANSACTION_DAY"
#define TRANSACTIONS_TABLE_DAY @"TIME_DAY"
#define TRANSACTIONS_TABLE_TIME @"TIME_TIME"
#define TRANSACTIONS_TABLE_TRANSACTIONS_QUANTITY @"TRANSACTION_QUANTITY"
#define TRANSACTIONS_TABLE_COST_VALUE_EXC @"COST_VALUE_EXCLUSIVE"
#define TRANSACTIONS_TABLE_SALES_VALUE_EXC @"SALES_VALUE_EXCLUSIVE"
#define TRANSACTIONS_TABLE_TRANSACTION_TYPE @"TRANSACTION_TYPE"

//TABLE NAME
#define LEAD_TIME_TABLE @"LEAD_TIME"
//TABLE ROWS
#define LEAD_TIME_TABLE_STORE_CODE @"STORE_CODE"
#define LEAD_TIME_TABLE_TRANSACTION_ID @"TRANSACTION_ID"
#define LEAD_TIME_TABLE_ORDER_DATE @"ORDER_DATE"
#define LEAD_TIME_TABLE_RECEIPT @"RECIEPT_DATE"

//TABLE NAME
#define PROMOTION_TABLE @"PROMOTION"
//TABLE ROWS
#define PROMOTION_TABLE_SUPPLIER_CODE @"SUPPLIER_CODE"
#define PROMOTION_TABLE_SUPPLIER_NAME @"TRADE_NAME"
#define PROMOTION_TABLE_PROMOTION_ID @"PROMOTION_ID"
#define PROMOTION_TABLE_BRAND @"BRAND"
#define PROMOTION_TABLE_SUPPLIER_PART_NO @"SUPPLIER_PART_NO"
#define PROMOTION_TABLE_PROMOTION_DETAILS @"PROMOTION_DETAILS"
#define PROMOTION_TABLE_BUY_PRICE @"PROMO_BUY_PRICE"
#define PROMOTION_TABLE_SELL_EX_GST @"PROMO_SELL_EX_GST"
#define PROMOTION_TABLE_SELL_INC_GST @"PROMO_SELL_INC_GST"
#define PROMOTION_TABLE_PAGE_NO @"PROMO_PAGE_NO"

